#!/usr/bin/env bash
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

script_dir="$( cd "$(dirname "$0")" ; pwd -P )"
source_dir=$(realpath "$script_dir/../")/
brc_username=`cat "$script_dir/savio_config/savio_username"`
dgx_deploy_dir="~/worktree/AA229FinalProject.jl"
savio_deploy_dir="~/worktree/AA229FinalProject.jl"
